---
- name: Deploy Artifact
  hosts: _API
  remote_user: ubuntu
  become: yes
  
  tasks:
      
  - name: Remove app folder if exists
    shell:
      cmd: rm -rf /home/ubuntu/app
      
  - name: Create clean app folder
    shell:
      cmd: mkdir -p /home/ubuntu/app
  
  - name: install unzip
    apt:
      name: unzip
      update_cache: yes
      
    
  - name: Extract API.zip on app folder
    unarchive:
      src: ~/API.zip
      dest: /home/ubuntu/app
      